delete https://artist-api.bannisterwebservices.co.uk/image/64edae6c114cf4ae44da2db1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcnRpc3QiOiJNYXR0X1BhZ2V0dCJ9.l44myyxCBHmCpWEYDpVSFexuz4sP5uFHs4x5Ps136Tk