put http://localhost:5000/image/6470a569502b50e71d2a21be
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcnRpc3QiOiJNYXR0IFBhZ2V0dCJ9.oF_LJAitBBCoa5RO3qzqFOYrPZIAgHAPreBVEXsbOUM
Content-Type: application/json

{
  "name": "update mc update face"
}