name: deploy to lambda
on:
    push:
        branches:
            - main
jobs:
    lambda:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2
            - run: zip -j lambdaAPI.zip ./lambdaAPI.py
            - run: aws lambda update-function-code --function-name=ArtistAPI --zip-file=fileb://lambdaAPI.zip